### PR TITLE
Kraken order mode backend

### PR DESCRIPTION
**Pull request by goodboy**
Replaces #214 since we're still waiting on history updates there 😉 

This PR isn't necessarily the one that will get merged but at the least is rebased onto recent `master` so we can see an up to date diff and append some commits as needed to get work from #214 to a testable phase.

ping @iamzoltan

### CODE REVIEW

**Comment by iamzoltan** [comment]
looks good to me

**Comment by iamzoltan** [comment]
You killed Philly, you bastard!

**Comment by goodboy** [comment]
Rebased this again onto master.
Still waiting on the original source branch to show approximately this history 😉

**Comment by goodboy** [comment]
Deferring back to #214.

**Pull request closed without merging**
