### PR TITLE
Order pane fixes

### PR DESCRIPTION
**Pull request by goodboy**
Miscellaneous fixes for the order mode pane UI.

Summary:
- fix a couple edge cases for discrete tradables (eg. stocks) where on a final exit of a single unit rounding logic caused a zero size and another case where a short sized negative `int` would generally mess up exit (buying to cover) sizing. 
- fixed some pnl label task startup/resume logic and label re-sizing issues that stemmed from increasing the number of shown digits on magnitude steps (eg. 0-9 -> 10-99 would cause label resizes which were quite obnoxious).
- drop use of `Enum` from the allocator (can't seem to make any sense of how `pydantic` expects you to use it..)
- expect a `tuple` of accounts from the EMS (instead of a set) in order to both preserve the user's config order of names as well as not break `msgpack` 😂.

### CODE REVIEW

**Comment by iamzoltan** [comment]
looks better! the added comments help provide some clarity and I like the cleaned up naming. Will pull and test it ooot!

**Comment by goodboy** [comment]
> Will pull and test it ooot!

just don't pull too hard.

**Comment by goodboy** [comment]
@iamzoltan ok master should be fixed once we land #241 now and this has been rebased onto that.

**Comment by iamzoltan** [comment]
tested it out, works now! thanks. good to merge imo

**Pull request merged**
